Update set-live to validate blue/green options

diff --git a/finish/set-live b/finish/set-live
--- a/finish/set-live
+++ b/finish/set-live
@@ -8,12 +8,15 @@ if [ "$LIVE_DEPLOYMENT" = "blue" ]; then
 	TEST_WEIGHT_BLUE=0
 	TEST_WEIGHT_GREEN=100
 	echo "Setting blue as live..."
-else
+elif [ "$LIVE_DEPLOYMENT" = "green" ]; then
 	WEIGHT_BLUE=0
 	WEIGHT_GREEN=100
 	TEST_WEIGHT_BLUE=100
 	TEST_WEIGHT_GREEN=0
 	echo "Setting green as live..."
+else
+  echo "$LIVE_DEPLOYMENT is an invalid option"
+  exit 1
 fi
 
 
